### ISSUE TITLE
STDERR: find: paths must precede expression: 2>/dev/null

### ISSUE THREAD

**Issue by finferflu** [sous-chefs/selinux_policy#104]
### Cookbook version
2.3.2, 2.3.3

### Chef-client version
14.10.9

### Platform Details
CentOS 7

### Scenario:
```
selinux_policy_fcontext '/var/www/vhosts/application/var(/.*)?' do
  secontext 'httpd_sys_rw_content_t'
end
```

### Steps to Reproduce:
This cookbook is used with Packer and chef-solo provider to build an Amazon Machine Image (AMI).

### Expected Result:
The cookbook should converge with no issues, as it did up until very recently.

### Actual Result:
Reported error during Packer build:
```
    amazon-ebs: ---- Begin output of ["find", "/var/www/vhosts/application", "-ignore_readdir_race", "-regextype", "posix-egrep", "-regex", "/var/www/vhosts/application/var(/.*)?", "-prune", "-print0", "2>/dev/null", "|", "xargs", "-0", "-I", "{}", "restorecon", "-iRv", "{}"] ----
    amazon-ebs: STDOUT:
    amazon-ebs: STDERR: find: paths must precede expression: 2>/dev/null
    amazon-ebs: Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
    amazon-ebs: ---- End output of ["find", "/var/www/vhosts/application", "-ignore_readdir_race", "-regextype", "posix-egrep", "-regex", "/var/www/vhosts/application/var(/.*)?", "-prune", "-print0", "2>/dev/null", "|", "xargs", "-0", "-I", "{}", "restorecon", "-iRv", "{}"] ----
    amazon-ebs: Ran ["find", "/var/www/vhosts/application", "-ignore_readdir_race", "-regextype", "posix-egrep", "-regex", "/var/www/vhosts/application/var(/.*)?", "-prune", "-print0", "2>/dev/null", "|", "xargs", "-0", "-I", "{}", "restorecon", "-iRv", "{}"] returned 1
```

Please note that the issue happened without me updating the cookbook (I was using version 2.3.2 for a while, and only attempted to use 2.3.3 to see whether this behaviour would still appear). The last successful build was around 20 days ago with Chef client version 14.8.12. Will the client affect the way the cookbook is run?

**Comment by finferflu** [comment]
I have just tested another build with Chef client version 14.8.12 and selinux_policy 2.3.2, and I get the same error as described above. More context:

```
    amazon-ebs:     System Info:
    amazon-ebs:     ------------
    amazon-ebs:     chef_version=14.8.12
    amazon-ebs:     platform=centos
    amazon-ebs:     platform_version=7.6.1810
    amazon-ebs:     ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    amazon-ebs:     program_name=/bin/chef-client
    amazon-ebs:     executable=/opt/chef/bin/chef-client
```

**Comment by damacus** [comment]
Thanks for such a detailed issue! 

I'll ping some of the other active community members who understand selinux better! :)

**Comment by damacus** [comment]
@Techcadia @Stromweld

**Comment by finferflu** [comment]
Thanks for the speedy reply, @damacus. From what I gather, I think this is more of an issue with `find`, rather than SELinux itself. It looks like `find` is having trouble with the `2>/dev/null` bit of the command.

**Comment by Stromweld** [comment]
I'm definitely not an selinux expert but it looks to be more of a logic issue with this block https://github.com/sous-chefs/selinux_policy/blob/master/resources/fcontext.rb#L16-L36 and then the shell_out!() to find command

**Comment by hexmoose** [comment]
The recent update assumes the `shell_out!` command is run in a shell, but it is not when called like it is with multiple args (see https://ruby-doc.org/core-2.6.1/Kernel.html#method-i-exec that is used by `shell_out!` internally). I'd suggest something like this as a fix:

    diff --git a/resources/fcontext.rb b/resources/fcontext.rb
    index 295e7aa..060ccae 100644
    --- a/resources/fcontext.rb
    +++ b/resources/fcontext.rb
    @@ -30,7 +30,7 @@ action :relabel do
         common = '/' if common[0] != '/'

         if ::File.exist? common
    -      shell_out!('find', common, '-ignore_readdir_race', '-regextype', 'posix-egrep', '-regex', spec, '-prune', '-print0', '2>/dev/null', '|', 'xargs', '-0', '-I', '{}', 'restorecon', '-iRv', '{}')
    +      shell_out!("find #{common.shellescape} -ignore_readdir_race -regextype posix-egrep -regex #{spec.shellescape} -prune -print0 2>/dev/null | xargs -0 restorecon -iRv")
         end
       end
     end

**Comment by Techcadia** [comment]
Interesting that this is broken in 2.3.2 which was before the merge of #91. I agree after looking at what @hexmoose wrote that we should still use the corrected `shell_out`. I have applied his diff
https://github.com/Techcadia/selinux_policy/tree/fix/shell_out

Still trying to repo the actual stated bug.

**Comment by hexmoose** [comment]
Thanks, @Techcadia. FWIW, I am only seeing the bug in 2.3.3, not 2.3.2.

**Comment by Techcadia** [comment]
@hexmoose Cool that makes much more sense. I have attached the PR @damacus.

Not sure how this got lost when I did my original testing.

**Comment by hexmoose** [comment]
@Techcadia, one other minor thing to note is that I tweaked the `xargs` command to remove the `-I {}`. It seems redundant to me, but perhaps you've encountered a use case that necessitates it? Just trying to prevent any other accidental regression. Thanks for prepping a PR for this fix.

**Comment by Techcadia** [comment]
I have not encountered any issue I was just working with the older code that had it written that way.
```
diff <(find / -ignore_readdir_race -regextype posix-egrep -regex "/app/example(/.*)?" -prune -print0 2>/dev/null | xargs -0 -I {} echo {}) <(find / -ignore_readdir_race -regextype posix-egrep -regex "/app/example(/.*)?" -prune -print0 2>/dev/null | xargs -0 echo)
```
are equal so I don't see this causing an issue. 

I have confirmed that is was introduced in #91 

Running against 2.3.3 causes the issue on a kitchen run.
Running against #105 which will become 2.3.4 no longer has the issue on a kitchen run.

As someone that has dealt with community cookbooks blowing up. I want to apologize for breaking it.

**Comment by finferflu** [comment]
Hi folks,

Thank you very much for the quick action on this issue. I just wanted to confirm that I've been misleading when I said the bug was present in version `2.3.2`. In fact, I had not realised I had that I had the pessimistic operator (`cookbook 'selinux_policy', '~> 2.3.2'`), so I was testing against version `2.3.3`. Apologies for the confusion!
