### ISSUE TITLE
Amazon Linux 2 not supported

### ISSUE THREAD

**Issue by TomGMan** [sous-chefs/selinux_policy#111]
https://github.com/sous-chefs/selinux_policy/blob/d3868fd5a4581d2c73ea102950a5c1aef04d9587/resources/install.rb#L4-L31

Amazon Linux 2 has platform_family `amazon`, whereas Amazon Linux (1) reports this as `rhel`

This makes this recipe fail on Amz Linux 2 instances.
```
when 'amazon'
 package ['policycoreutils-python', 'selinux-policy-devel', 'setools-console', 'make'] 
```

**Comment by damacus** [comment]
Hi!
which version of ohai, and Chef-client are you using?

Amazon-1 and Amazon-2 should both be reporting as platform_family amazon

**Comment by TomGMan** [comment]
Ohai: 8.26.1
Chef:12.22.5 
I'm aware this is EOL.

Regardless of @damacus ' comment, the cookbook will still fail.

**Comment by damacus** [comment]
If you can provide replication steps on a non-EOL version of Chef then we'll happily take a look. 

Right now we only support Chef 13 and 14. Soon to be Chef 14 and 15

**Comment by TomGMan** [comment]
Replication: Amazon Linux 2 box
Install Chef 14.
Use recipe that has a dependency on this cookbook.
See it fail.

don't see why/how Chef 12 would be relevant as the platform_family for amazon linux is simply not in the code and therefore it will always fail ever since the update was pushed through in Chef to list Amz Linux as "amazon" platform family.
