### ISSUE TITLE
SE Port Management Fails on CentOS 8

### ISSUE THREAD

**Issue by brownc** [sous-chefs/selinux_policy#129]
## :ghost: Brief Description

When trying to manage selinux ports on CentOS 8, a port that already has been assigned to a type will cause a chef-client run to fail.

## :pancakes: Cookbook version

selinux_policy        2.3.4

## :woman_cook:  Chef-Infra Version

Chef Infra Client: 15.6.10

## :tophat: Platform details

```
$ cat /etc/centos-release
CentOS Linux release 8.0.1905 (Core)
$ uname -a
Linux centos8host.local 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -qa | grep setools-console
setools-console-4.2.0-2.el8.x86_64
```

On-prem VMware instance.

## Steps To Reproduce

Recipe use of `selinux_policy_port`

```
# Configure the SSH port in SELinux
selinux_policy_port '122' do
  protocol 'tcp'
  secontext 'ssh_port_t'
end
```

Then on a CentOS 8 machine, run `chef-client` twice - once to do the original add, then again to trip the error because the port already exists when trying to re-add.

## :police_car: Expected behavior

Based on CentOS 7 once Chef has run successfully once, the helper `port_defined` should complete successfully and report the group like so:

```
$ sudo seinfo --portcon=122 --protocol=tcp |  awk -F: '$(NF-1) !~ /reserved_port_t$/ && $(NF-3) !~ /[0-9]*-[0-9]*/ {print $(NF-1)}'
ssh_port_t
```

CentOS 7 details:

```
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
$ uname -a
Linux centos7host.local 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[srvadmin@mxdockt01 ~]$ rpm -qa | grep setools
setools-libs-3.3.8-4.el7.x86_64
setools-console-3.3.8-4.el7.x86_64
[srvadmin@mxdockt01 ~]$ rpm -qa | grep setools-con
setools-console-3.3.8-4.el7.x86_64
[srvadmin@mxdockt01 ~]$ rpm -qa | grep setools-consol
setools-console-3.3.8-4.el7.x86_64
```

## :police_car: Actual behavior

The CentOS 8 chef-client run fails with the attached (too long to post) stack trace of errors.
[selinux_stack_trace.txt](https://github.com/sous-chefs/selinux_policy/files/4024178/selinux_stack_trace.txt)

Most noticeable error in the output:

```
* execute[selinux-port-122-add] action run[2020-01-05T22:28:52+00:00] INFO: Processing execute[selinux-port-122-add] action run (/var/chef/cache/cookbooks/selinux_policy/resources/port.rb line 21)
[2020-01-05T22:28:52+00:00] INFO: Processing execute[Guard resource] action run (dynamically defined)
usage: seinfo [-h] [--version] [-x] [--flat] [-v] [--debug] [-a [ATTR]]
          [-b [BOOL]] [-c [CLASS]] [-r [ROLE]] [-t [TYPE]] [-u [USER]]
          [--category [CAT]] [--common [COMMON]] [--constrain [CLASS]]
          [--default [CLASS]] [--fs_use [FS_TYPE]] [--genfscon [FS_TYPE]]
          [--initialsid [NAME]] [--netifcon [DEVICE]] [--nodecon [ADDR]]
          [--permissive [TYPE]] [--polcap [NAME]]
          [--portcon [PORTNUM[-PORTNUM]]] [--sensitivity [SENS]]
          [--typebounds [BOUND_TYPE]] [--validatetrans [CLASS]] [--all]
          [--ioportcon] [--iomemcon] [--pcidevicecon] [--pirqcon]
          [--devicetreecon]
          [policy]
seinfo: error: unrecognized arguments: --protocol=tcp
```

## :heavy_plus_sign: Additional context

There's two potential things here as a result of moving to CentOS 8:

1. There is `--protocol` flag for the `semanage` command the library helpers are trying to use, so we're erroring out there.
2. When troubleshooting, if I drop the `--protocol` (so I may get other protocols/ports/etc), other than the padding on the output lines I can't see a format change.  I'm pretty rubbish when it comes to `awk` but wonder if something has changed there too on top of 1 above?

If relevant, CentOS 7 => GNU Awk 4.0.2, CentOS 8 => GNU Awk 4.2.1.

Thanks!

**Comment by Vancelot11** [comment]
I believe this issue can be close since #131 got merged.
