### ISSUE TITLE
Better check for which folder to relabel possible?

### ISSUE THREAD

**Issue by daften** [sous-chefs/selinux_policy#56]
This is more a question than an issue, because nothing is truly broken.
I have a fcontext for /var/lib/mysql-default(/.*)?
The relabel for this is a restorecon on /var/lib

Could the code that checks the path be rewritten so the restorecon would be done on /var/lib/mysql-default? Is there a list of special regex characters that could be trimmed from the end that should never be in folder names?

The question comes because a restorecon on /var/lib takes reaaaaally long

The fact that the condition uses the same command while not changing anything, doesn't help either. As far as I can see ATM this only means a run almost twice as long (in my case).

**Comment by BackSlasher** [comment]
Hi @daften. I think we can modify [this code](https://github.com/BackSlasher/chef-selinuxpolicy/blob/8702b08/providers/fcontext.rb#L28) to run on the actual files. Maybe something with `find STUFF | xargs restorecon -R`
Will you manage a PR?

**Comment by BackSlasher** [comment]
[linked above](https://github.com/BackSlasher/chef-selinuxpolicy/blob/8702b08/providers/fcontext.rb#L28)

**Comment by atward** [comment]
To rephrase, I'd like to see the _recipe_ that causes it to relabel over `/var/lib`. As per [the command generator](https://github.com/BackSlasher/chef-selinuxpolicy/blob/8702b08/providers/fcontext.rb#L22) it should only do that if `mysql-default` does not exist. This check/command-generation is done at compile time, hence my suggestion for `lazy { }`

**Comment by BackSlasher** [comment]
Aha. @daften can you provide a use-case?
Also, I don't see the reason for ever running on `/var/lib`, but I might be missing something

**Comment by BackSlasher** [comment]
I think the issue back then was that the SELinux's regex didn't match `find`'s regex

**Comment by atward** [comment]
Re: restorecon taking a long time. As @daften said, the relabel execute resource actually runs it twice (due to guard).

I also agree that the guard should be removed. The only caveat is this will cause the resource to always flag as being updated. To fix you would have to convert the execute to a shell_out and check length of stdout.

**Comment by BackSlasher** [comment]
Well, I think I'll accept PRs on that

**Comment by daften** [comment]
This is the regex why it falls back to /var/lib:
```
selinux_policy_fcontext "/var/lib/mysql-default(/.*)?" do
  secontext "mysqld_db_t"
end
```
It is like this because all subfolders need to get the mysql_db_t label.
What happens now is that the first parts splits on the last / it finds, so it remains with /var/lib/mysql-default( which is off course not a real folder, so it splits again on /, which gets it /var/lib.

And agreed with @atward , the guard doesn't really make sense here, since it does the same thing as the real resource execution, except simulating it instead of doing it (and in this case, it's not faster unfortunately).

I want to make a PR, but I'd like feedback on this first ;)

**Comment by atward** [comment]
Removal of guard included in #57

**Comment by atward** [comment]
@daften, the problem is that the cookbook has no way of knowing what is the highest possible path given a regex. Take for example the following:

```
selinux_policy_fcontext "/var/lib/mysql-(default|dist)(/.*)?" do
  secontext "mysqld_db_t"
end
```

The best the code can do is check for the existence of files/directories that match the regex, and then apply to that (which it is doing by `File.directory?`).

If you use the lazy change from #57, and put a `directory  '/var/lib/mysql-default'` prior to your `selinux_policy_fcontext` it should only run `restorecon -iR /var/lib/mysql-default`. I suspect you current code is installing mysql after the selinux changes.

**Comment by daften** [comment]
Nope, I get these results on all runs, not just the first that installs MySQL.
And I understand what the problem is, it can't detect the /var/lib/mysql-default  as a folder, but what you're suggesting won't fix that. The folder IS already there, but because of the way it parses the regex: splitting on '/', it doesn't try to check if /var/lib/mysql-default exists, it checks if /var/lib/mysql-default( with the opening parenthesis exists. ;)

**Comment by atward** [comment]
I see it now.

Find should suit as suggested earlier, but will need to set regextype. I'm not sure if this will have compat issues (requires find 4.2.24+)

    find / -regextype posix-egrep -regex '#{new_resource.file_spec}' -print0  2>/dev/null | xargs -0 restorecon -i

**Comment by BackSlasher** [comment]
RE compat, I have a supported OS list. If it passes testing, I'm happy

**Comment by daften** [comment]
How about
```
find / -regextype posix-egrep -regex '/var/lib/mysql-default(/.*)?' -type d -print0  2>/dev/null | xargs -0 restorecon -iR
```
Or do you reckon this will get too many doubles. With find i'm worried we'll miss hidden files

**Comment by daften** [comment]
Just checked and the find is extremely fast in both cases now (as it should be).
I'll look into a PR, but would prefer to start it when there's consensus on #57
