### ISSUE TITLE
shellout to find is traversing /proc

### ISSUE THREAD

**Issue by acranox** [sous-chefs/selinux_policy#71]
This is kind of crazy:
https://github.com/sous-chefs/selinux_policy/blob/master/providers/fcontext.rb#L41

You occasionally run into errors like this:

```
[15:08:20][Step 4/7]          ---- Begin output of ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/cache/nova(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] ----
[15:08:20][Step 4/7]          STDOUT: 
[15:08:20][Step 4/7]          STDERR: find: ‘/proc/11889’: No such file or directory
[15:08:20][Step 4/7]          ---- End output of ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/cache/nova(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] ----
[15:08:20][Step 4/7]          Ran ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/cache/nova(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] returned 1
```

If you're going to shellout to find, you could determine the filesystem you need to search, and then use -xdev to avoid crossing filesystem boundaries, otherwise you could start searching large network storage, or hitting issues like this with ephemeral files in /proc.

Also using -execdir {}; forks for each file found.  xargs or {}+ passes multiple arguments to the utility being invoked, thereby reducing overhead.

**Comment by shortdudey123** [comment]
@daften can you take a look at this? thoughts?

**Comment by BackSlasher** [comment]
lol
We should probably add `-xdev` (Don't descend directories on other
filesystems.)
Should have thought about that

*Nitzan Raz*
http://backslasher.net

**Comment by shortdudey123** [comment]
Ah, did not know about the `-xdev` option :)

**Comment by BackSlasher** [comment]
@acranox you have a chance at everlasting glory here. Translate your recommendations into a PR and submit! :smile:

**Comment by shortdudey123** [comment]
One thought though... if the find is executed on `/` like it currently is and you add `-xdev` then won't the find fail if the directly (`new_resource.file_spec`) is not on the root partition?

**Comment by BackSlasher** [comment]
that's true. We should probably eliminate virtual filesystems though.

**Comment by acranox** [comment]
That's correct, about running find on / if your resource isn't in that FS.
You'll need to determine what filesystem new_resource.file_spec is on first.
Don't count on me for a PR.  at least not in a timely fashion.  :)

**Comment by shortdudey123** [comment]
Probably can use `df <dir>` and parse the mount point

**Comment by BackSlasher** [comment]
I might still want to operate on other filesystems.
I think the best solution would be to avoid doing smart things, and having
some attribute ("restorecon_single_filesystem") to add this behavior.
Maybe we can by default avoid proc with something like this
https://unix.stackexchange.com/a/193277

*Nitzan Raz*
http://backslasher.net

**Comment by acranox** [comment]
stat --format '%m' <file>  might be lighter weight than df.

**Comment by acranox** [comment]
I got bit by this again today.  It looks like the find command starting traversing into an Amazon EFS volume, and after 600s, it timed out and the chef run failed.  I created a PR that may address it.

**Comment by damacus** [comment]
See #72

**Comment by chewi** [comment]
This can be closed now.
