### ISSUE TITLE
setsebool - No such file or directory

### ISSUE THREAD

**Issue by tnguyen14** [sous-chefs/selinux_policy#93]
### Cookbook version
2.1.0

### Chef-client version
14.2

### Platform Details
RHEL 7

### Scenario:
I have the following resource to enable support for NGINX

```
selinux_policy_boolean 'httpd_can_network_connect' do
  value true
end
```

### Expected Result:
This works every time.

### Actual Result:
It works on the first chef run, but on some later chef runs, I get this error instead:

```
selinux_policy_boolean[httpd_can_network_connect] (cookbook::nginx line 26) had an error: Errno::ENOENT: execute[selinux-setbool-httpd_can_network_connect-on] (/var/chef/cache/cookbooks/selinux_policy/providers/boolean.rb line 21) had an error: Errno::ENOENT: No such file or directory - setsebool
```

**Comment by tnguyen14** [comment]
I think this might be related to #85

**Comment by sspans** [comment]
I guess this can be closed.
